script/makeConfigAudio.sh analyze_print.h
script/makeConfigAudio.sh control_wm8731.h 
script/makeConfigAudio.sh effect_flange.h
script/makeConfigAudio.sh filter_variable.h      
script/makeConfigAudio.sh play_fs_wav.h
script/makeConfigAudio.sh synth_karplusstrong.h
script/makeConfigAudio.sh synth_whitenoise.h
script/makeConfigAudio.sh analyze_rms.h
script/makeConfigAudio.sh effect_bitcrusher.h
script/makeConfigAudio.sh effect_midside.h
script/makeConfigAudio.sh input_adcs.h
script/makeConfigAudio.sh play_memory.h          
script/makeConfigAudio.sh synth_pinknoise.h
script/makeConfigAudio.sh analyze_tonedetect.h   
script/makeConfigAudio.sh effect_multiply.h      
script/makeConfigAudio.sh input_i2s.h            
script/makeConfigAudio.sh play_queue.h           
script/makeConfigAudio.sh synth_pwm.h
script/makeConfigAudio.sh analyze_fft1024.h      
script/makeConfigAudio.sh control_ak4558.h       
script/makeConfigAudio.sh effect_delay.h         
script/makeConfigAudio.sh effect_reverb.h        
script/makeConfigAudio.sh play_sd_raw.h          
script/makeConfigAudio.sh synth_simple_drum.h
script/makeConfigAudio.sh analyze_fft256.h
script/makeConfigAudio.sh control_cs42448.h      
script/makeConfigAudio.sh effect_delay_ext.h     
script/makeConfigAudio.sh effect_waveshaper.h    
script/makeConfigAudio.sh mixer.h                
script/makeConfigAudio.sh record_queue.h         
script/makeConfigAudio.sh synth_sine.h
script/makeConfigAudio.sh analyze_notefreq.h     
script/makeConfigAudio.sh control_cs4272.h       
script/makeConfigAudio.sh effect_envelope.h      
script/makeConfigAudio.sh filter_biquad.h        
script/makeConfigAudio.sh output_dacs.h          
script/makeConfigAudio.sh synth_tonesweep.h
script/makeConfigAudio.sh analyze_peak.h         
script/makeConfigAudio.sh control_sgtl5000.h     
script/makeConfigAudio.sh effect_fade.h          
script/makeConfigAudio.sh filter_fir.h           
script/makeConfigAudio.sh output_i2s.h           
script/makeConfigAudio.sh synth_dc.h             
script/makeConfigAudio.sh synth_waveform.h
